version: "3"

services:
  db:
    container_name: mysql-db
    build:
      context: ./db
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3306:3306"

  server:
    container_name: graphql-server
    build:
      context: ./go
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
