package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.34

import (
	"context"

	"graphql_server/graph/model"
	"graphql_server/internal"
	"math"
)

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, name string) (*model.User, error) {
	return r.Srv.CreateUser(ctx, name)
}

// DeleteUser is the resolver for the deleteUser field.
func (r *mutationResolver) DeleteUser(ctx context.Context, id string) (*model.User, error) {
	return r.Srv.DeleteUser(ctx, id)
}

// UpdateUser is the resolver for the updateUser field.
func (r *mutationResolver) UpdateUser(ctx context.Context, id string, name string) (*model.User, error) {
	return r.Srv.UpdateUser(ctx, id, name)
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, id string) (*model.User, error) {
	return r.Srv.GetUser(ctx, id)
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context, limit *int) ([]*model.User, error) {
	if limit == nil {
		limit = new(int)
		*limit = math.MaxInt32
	}
	return r.Srv.GetUsers(ctx, *limit)
}

// UsersByID is the resolver for the usersByID field.
func (r *queryResolver) UsersByID(ctx context.Context, ids []string) ([]*model.User, error) {
	thunk := r.Loaders.UserLoader.LoadMany(ctx, ids)
	users, errs := thunk()
	if len(errs) > 0 {
		return nil, errs[0]
	}
	return users, nil
}

// Mutation returns internal.MutationResolver implementation.
func (r *Resolver) Mutation() internal.MutationResolver { return &mutationResolver{r} }

// Query returns internal.QueryResolver implementation.
func (r *Resolver) Query() internal.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
