package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.34

import (
	"context"
	"graphql_server/graph/model"
	"graphql_server/internal"
)

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, id string) (*model.User, error) {
	return r.Srv.GetUser(ctx, id)
}

// UsersByID is the resolver for the usersByID field.
func (r *queryResolver) UsersByID(ctx context.Context, ids []string) ([]*model.User, error) {
	thunk := r.Loaders.UserLoader.LoadMany(ctx, ids)
	users, errs := thunk()
	if len(errs) > 0 {
		return nil, errs[0]
	}
	return users, nil
}

// Query returns internal.QueryResolver implementation.
func (r *Resolver) Query() internal.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
