FROM mysql:8.0

ENV MYSQL_DATABASE=mydb
ENV MYSQL_USER=testuser
ENV MYSQL_PASSWORD=mypassword
ENV MYSQL_ROOT_PASSWORD=mypassword

CMD ["--default-authentication-plugin=mysql_native_password"]

EXPOSE 3306
