linters:
    disable-all: true
    enable:
        - errcheck
        - gosimple
        - govet
        - ineffassign
        - staticcheck
        - typecheck
        - unused
        - gochecknoglobals
        - goconst
        - gofmt
        - gci
