name: OpenAI Reviewer

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
  pull_request_review_comment:
    types: [created]

concurrency:
  group: ${{ github.repository }}-${{ github.event.number || github.head_ref ||
    github.sha }}-${{ github.workflow }}-${{ github.event_name ==
    'pull_request_review_comment' && 'pr_comment' || 'pr' }}
  cancel-in-progress: ${{ github.event_name != 'pull_request_review_comment' }}

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: fluxninja/openai-pr-reviewer@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        with:
          debug: true
          review_simple_changes: true
          review_comment_lgtm: true
          openai_light_model: gpt-3.5-turbo-0613
          openai_heavy_model: gpt-3.5-turbo-0613
          system_message: | # PullRequestレビュー用
            - プロンプトを記載
            Important:
              Please write your review in Japanese.
          summarize: | # PullRequestコメント用
            - プロンプトを記載
            Important:
              Please write your summary in Japanese.
          summarize_release_notes: | # リリースノート用
            - プロンプトを記載
            Important:
              Please write your release notes in Japanese.
